services:
  backend-locar:
    image: locar-be-dev
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_KEY=${API_KEY}
      - JWT_KEY=${JWT_KEY}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKOFFICE_URL=${BACKOFFICE_URL}
      - CLOUDINARY_SECRET_KEY=${CLOUDINARY_SECRET_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - CONTACT_PHONE=${CONTACT_PHONE}
      - FLUTTERWAVE_PUBLIC_KEY=${FLUTTERWAVE_PUBLIC_KEY}
      - DATOCMS=${DATOCMS}
      - APP_URL_BACKEND=${APP_URL_BACKEND}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - IMAGE_BASE_URL=${IMAGE_BASE_URL}
      - MAILJET_KEY=${MAILJET_KEY}
      - MAILJET_SECRETKEY=${MAILJET_SECRETKEY}
      - MAILJET_EMAIL_SENDER=${MAILJET_EMAIL_SENDER}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - KPAY_USERNAME=${KPAY_USERNAME}
      - KPAY_PASSWORD=${KPAY_PASSWORD}
      - KPAY_RETAILERID=${KPAY_RETAILERID}
      - KPAY_BANKID_MOBILE_MONEY=${KPAY_BANKID_MOBILE_MONEY}
      - KPAY_BANKID_AIRTEL_MONEY=${KPAY_BANKID_AIRTEL_MONEY}
      - KPAY_ALLOWED_TOPUP_PAYMENT_METHOD=${KPAY_ALLOWED_TOPUP_PAYMENT_METHOD}
      - ONESIGNAL_APP_ID=${ONESIGNAL_APP_ID}
      - ONESIGNAL_URL=${ONESIGNAL_URL}
    ports:
      - 4001:4001
    volumes:
      - ./node_modules:/app/node_modules
