# fly.toml file generated for locar-be on 2022-12-23T09:39:54+02:00

app = "${FLY_APP_NAME}"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "4001"

[env.staging]
  FLY_APP_NAME = "locar-be"
  NODE_ENV = "development"

[env.production]
  FLY_APP_NAME = "reach-prod"
  NODE_ENV = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4001
  memory = "1G"
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  command = "./build/index.js"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [services.volumes]
    # mount node_modules from the host to the container
    source = "./node_modules"
    target = "/app/node_modules"
    readonly = true
